/* ============================================================
   TREAGE v1.1.0 — Interactive Decision Tree Framework Engine
   https://github.com/rseldner/treage

   Load AFTER d3 and AFTER your CONFIG + TREE definitions.
   This file owns: DOM shell, all CSS, layout, rendering,
   interactive mode, theme toggle, zoom/pan, and init.

   You supply (in your consumer file, before this script):
     const CONFIG = { ... };   // meta, palettes, nodeTypes
     const TREE   = { ... };   // your tree data

   DO NOT EDIT THIS FILE to customise your tree.
   Edit CONFIG and TREE in your own file instead.
   To upgrade: replace this file with the new version.
   ============================================================ */

(function () {
'use strict';

const TREAGE_STYLES = `
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&family=IBM+Plex+Sans:wght@300;400;500;600&display=swap" rel="stylesheet">
<style id="treage-styles">
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html, body { width: 100%; height: 100%; overflow: hidden; }
body {
  font-family: var(--font-body, 'IBM Plex Sans', sans-serif);
  background: var(--color-bg, #0d0f14);
  color: var(--color-text, #e8eaf0);
  display: flex; flex-direction: column;
  transition: background 0.25s ease, color 0.25s ease;
}
body::before {
  content: '';
  position: fixed; inset: 0;
  background-image:
    linear-gradient(var(--grid-line, rgba(255,255,255,0.018)) 1px, transparent 1px),
    linear-gradient(90deg, var(--grid-line, rgba(255,255,255,0.018)) 1px, transparent 1px);
  background-size: 40px 40px;
  pointer-events: none; z-index: 0;
  transition: opacity 0.25s ease;
}
#treage-app { position: relative; z-index: 1; display: flex; flex-direction: column; height: 100%; overflow: hidden; }
/* ── Header ── */
header {
  display: flex; align-items: center; gap: 16px;
  padding: 0 28px; height: 60px;
  border-bottom: 1px solid var(--color-border, #252a38);
  flex-shrink: 0;
  background: var(--header-bg, rgba(13,15,20,0.95));
  backdrop-filter: blur(10px);
  transition: background 0.25s ease, border-color 0.25s ease;
}
.tg-header-icon { flex-shrink: 0; }
.tg-header-text h1 { font-size: 17px; font-weight: 600; letter-spacing: -0.2px; }
.tg-header-text p  { font-size: 12px; color: var(--color-muted, #7a8099); font-weight: 300; margin-top: 2px; }
/* ── Mode toggle ── */
.tg-mode-toggle {
  display: flex;
  background: var(--color-surface, #13161e);
  border: 1px solid var(--color-border, #252a38);
  border-radius: 8px; padding: 3px; gap: 3px;
  margin-left: 24px; flex-shrink: 0;
  transition: background 0.25s ease, border-color 0.25s ease;
}
.tg-mode-btn {
  padding: 5px 14px; border-radius: 5px; border: none;
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 11px; font-weight: 600; letter-spacing: 0.5px;
  text-transform: uppercase; cursor: pointer; transition: all 0.18s;
  color: var(--color-dim, #4a5068); background: transparent;
}
.tg-mode-btn.active { background: var(--color-border, #252a38); color: var(--color-text, #e8eaf0); }
.tg-mode-btn:not(.active):hover { color: var(--color-muted, #7a8099); }
/* ── Theme toggle ── */
.tg-theme-btn {
  width: 34px; height: 34px;
  display: flex; align-items: center; justify-content: center;
  background: var(--color-surface, #13161e);
  border: 1px solid var(--color-border, #252a38);
  border-radius: 8px; cursor: pointer; flex-shrink: 0;
  transition: all 0.18s; color: var(--color-muted, #7a8099); margin-left: 4px;
}
.tg-theme-btn:hover { border-color: var(--color-accent, #00bfb3); color: var(--color-accent, #00bfb3); }
.tg-theme-btn svg { width: 16px; height: 16px; transition: transform 0.35s ease; }
.tg-theme-btn:hover svg { transform: rotate(20deg); }
.tg-icon-moon { display: block; }
.tg-icon-sun  { display: none;  }
body.tg-light .tg-icon-moon { display: none;  }
body.tg-light .tg-icon-sun  { display: block; }
/* ── Legend ── */
.tg-legend { margin-left: auto; display: flex; gap: 18px; flex-wrap: wrap; align-items: center; }
.tg-legend-item {
  display: flex; align-items: center; gap: 6px;
  font-size: 10.5px; font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  color: var(--color-muted, #7a8099); text-transform: uppercase; letter-spacing: 0.5px;
}
.tg-legend-dot { width: 9px; height: 9px; border-radius: 50%; flex-shrink: 0; }
/* ── GitHub link ── */
.tg-github-link {
  display: flex; align-items: center; gap: 7px;
  color: var(--color-muted, #7a8099); text-decoration: none;
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 11px; font-weight: 600; letter-spacing: 0.5px; text-transform: uppercase;
  padding: 6px 12px;
  border: 1px solid var(--color-border, #252a38); border-radius: 7px;
  transition: all 0.18s; flex-shrink: 0; margin-left: 12px;
}
.tg-github-link:hover { color: var(--color-text, #e8eaf0); border-color: var(--color-accent, #00bfb3); }
/* ── Panels ── */
#tg-panel-tree, #tg-panel-interactive {
  flex: 1; overflow: hidden; display: none; flex-direction: column;
}
#tg-panel-tree.tg-visible { display: flex; }
#tg-panel-interactive.tg-visible { display: flex; overflow-y: auto; }
/* ── Full-tree canvas ── */
#tg-canvas { flex: 1; overflow: hidden; }
#tg-canvas svg { width: 100%; height: 100%; }
.tg-controls {
  position: absolute; bottom: 20px; right: 20px;
  display: flex; flex-direction: column; gap: 6px; z-index: 10;
}
.tg-ctrl-btn {
  width: 36px; height: 36px;
  background: var(--color-surface, #1a1e2a);
  border: 1px solid var(--color-dim, #3a4158);
  border-radius: 8px; color: var(--color-muted, #7a8099);
  font-size: 18px; cursor: pointer;
  display: flex; align-items: center; justify-content: center;
  transition: all 0.2s; font-family: monospace; line-height: 1; user-select: none;
}
.tg-ctrl-btn:hover { color: var(--color-text, #e8eaf0); border-color: var(--color-accent, #00bfb3); }
/* ── Node cards (full-tree SVG) ── */
.tg-node-card {
  width: 100%; height: 100%; border-radius: 10px; padding: 11px 14px;
  display: flex; flex-direction: column; justify-content: center; overflow: hidden;
}
.tg-card-eyebrow {
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 9.5px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px;
  margin-bottom: 5px; display: flex; align-items: center; gap: 5px;
}
.tg-new-badge {
  background: rgba(254,197,20,0.15); color: #fec514;
  border: 1px solid rgba(254,197,20,0.3);
  border-radius: 4px; font-size: 8px; padding: 1px 4px; letter-spacing: 0.5px;
}
.tg-card-title { font-size: 12px; font-weight: 500; line-height: 1.45; }
.tg-card-hint  { font-size: 10.5px; font-weight: 300; font-style: italic; margin-top: 5px; line-height: 1.4; }
.tg-edge-label {
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 10px; font-weight: 600; letter-spacing: 0.8px;
  text-transform: uppercase; pointer-events: none;
}
/* ── Interactive view ── */
.tg-interactive-inner { max-width: 680px; width: 100%; margin: 0 auto; padding: 32px 24px 48px; }
.tg-progress-row { display: flex; gap: 7px; align-items: center; margin-bottom: 24px; }
.tg-progress-dot { width: 8px; height: 8px; border-radius: 50%; transition: all 0.2s ease; cursor: pointer; }
.tg-breadcrumb {
  display: flex; flex-wrap: wrap; align-items: center;
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 11px; color: var(--color-dim, #4a5068); margin-bottom: 20px; gap: 2px;
}
.tg-crumb-link { cursor: pointer; text-decoration: underline; text-decoration-color: var(--color-border, #252a38); color: var(--color-dim, #4a5068); }
.tg-crumb-link:hover { color: var(--color-accent, #00bfb3); }
.tg-crumb-sep { color: var(--color-border, #252a38); margin: 0 4px; }
.tg-crumb-current { color: var(--color-accent, #00bfb3); }
.tg-i-card {
  background: var(--color-surface, #13161e);
  border: 1px solid var(--color-border, #1a1e2a);
  border-radius: 10px; padding: 28px 28px 24px;
  box-shadow: 0 4px 40px rgba(0,0,0,0.35);
  transition: background 0.25s ease, border-color 0.25s ease, box-shadow 0.25s ease;
}
.tg-i-step-label {
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px;
  color: var(--color-dim, #4a5068); margin-bottom: 10px;
  display: flex; align-items: center; gap: 7px;
}
.tg-i-question { font-size: 18px; font-weight: 500; color: var(--color-text, #e8eaf0); line-height: 1.5; margin: 0 0 10px; }
.tg-i-hint     { font-size: 12px; font-weight: 300; font-style: italic; color: var(--color-dim, #4a5068); line-height: 1.5; margin: 0 0 24px; }
.tg-options-row { display: flex; gap: 12px; flex-wrap: wrap; }
.tg-opt-btn {
  flex: 1; min-width: 120px; border-radius: 8px; padding: 14px 20px;
  font-size: 15px; font-weight: 600; font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  letter-spacing: 0.5px; cursor: pointer;
  display: flex; align-items: center; justify-content: center; gap: 8px;
  transition: all 0.15s ease;
  border: 1px solid var(--color-border, #252a38);
  background: var(--color-surface, #13161e); color: var(--color-text, #e8eaf0);
}
.tg-opt-btn.tg-yes:hover { background: rgba(61,214,140,0.07); border-color: var(--edge-yes, #3dd68c); color: var(--edge-yes, #3dd68c); transform: translateY(-2px); }
.tg-opt-btn.tg-no:hover  { background: rgba(255,107,107,0.07); border-color: var(--edge-no,  #ff6b6b); color: var(--edge-no,  #ff6b6b); transform: translateY(-2px); }
.tg-opt-icon { font-size: 15px; color: var(--color-dim, #3a4158); transition: color 0.15s; }
.tg-opt-btn.tg-yes:hover .tg-opt-icon { color: var(--edge-yes, #3dd68c); }
.tg-opt-btn.tg-no:hover  .tg-opt-icon { color: var(--edge-no,  #ff6b6b); }
.tg-outcome-card { border-radius: 10px; padding: 28px 28px 24px; box-shadow: 0 4px 40px rgba(0,0,0,0.35); }
.tg-outcome-badge {
  display: inline-block; font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px;
  padding: 3px 10px; border-radius: 4px; border: 1px solid; margin-bottom: 14px;
}
.tg-outcome-eyebrow {
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px;
  margin-bottom: 8px; display: flex; align-items: center; gap: 7px;
}
.tg-outcome-title { font-size: 15px; font-weight: 500; line-height: 1.55; margin: 0 0 14px; }
.tg-outcome-hint  { font-size: 12px; font-weight: 300; font-style: italic; line-height: 1.5; opacity: 0.65; }
.tg-back-btn {
  background: none; border: none; color: var(--color-dim, #4a5068);
  font-size: 13px; cursor: pointer; font-family: inherit;
  margin-top: 18px; padding: 0; transition: color 0.15s;
}
.tg-back-btn:hover { color: var(--color-accent, #00bfb3); }
.tg-reset-btn {
  display: inline-flex; align-items: center; gap: 6px;
  background: none; border: 1px solid var(--color-border, #252a38);
  border-radius: 6px; padding: 8px 14px; color: var(--color-muted, #7a8099);
  font-size: 12px; font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  text-transform: uppercase; letter-spacing: 0.5px;
  cursor: pointer; margin-top: 20px; transition: all 0.15s;
}
.tg-reset-btn:hover { color: var(--color-accent, #00bfb3); border-color: var(--color-accent, #00bfb3); }
/* ── Footer ── */
footer {
  flex-shrink: 0; display: flex; align-items: center; justify-content: center; gap: 16px;
  height: 36px; border-top: 1px solid var(--color-border, #252a38);
  background: var(--header-bg, rgba(13,15,20,0.95));
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 10px; color: var(--color-dim, #4a5068); letter-spacing: 0.5px;
  transition: background 0.25s ease, border-color 0.25s ease;
}
footer a { color: var(--color-dim, #4a5068); text-decoration: none; transition: color 0.15s; }
footer a:hover { color: var(--color-accent, #00bfb3); }
footer .tg-sep { color: var(--color-border, #252a38); }
</style>
`;

const TREAGE_BODY = `
<div id="treage-app">
  <header>
    <div class="tg-header-icon" id="tg-header-icon"></div>
    <div class="tg-header-text">
      <h1 id="tg-header-title"></h1>
      <p id="tg-header-sub"></p>
    </div>
    <div class="tg-mode-toggle">
      <button class="tg-mode-btn active" id="tg-btn-tree"        onclick="treage.setMode('tree')">Full Tree</button>
      <button class="tg-mode-btn"        id="tg-btn-interactive" onclick="treage.setMode('interactive')">Interactive</button>
    </div>
    <button class="tg-theme-btn" id="tg-theme-toggle" title="Toggle light / dark mode" onclick="treage.toggleTheme()">
      <svg class="tg-icon-moon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/>
      </svg>
      <svg class="tg-icon-sun" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <circle cx="12" cy="12" r="5"/>
        <line x1="12" y1="1"  x2="12" y2="3"/>  <line x1="12" y1="21" x2="12" y2="23"/>
        <line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/> <line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/>
        <line x1="1" y1="12" x2="3" y2="12"/>   <line x1="21" y1="12" x2="23" y2="12"/>
        <line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/> <line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/>
      </svg>
    </button>
    <div class="tg-legend" id="tg-legend"></div>
    <a class="tg-github-link" href="https://github.com/rseldner/treage" target="_blank" rel="noopener">
      <svg width="15" height="15" viewBox="0 0 24 24" fill="currentColor">
        <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0 0 24 12c0-6.63-5.37-12-12-12z"/>
      </svg>
      GitHub
    </a>
  </header>

  <div id="tg-panel-tree" class="tg-visible">
    <div id="tg-canvas"></div>
    <div class="tg-controls">
      <button class="tg-ctrl-btn" id="tg-zoom-in"  title="Zoom in">+</button>
      <button class="tg-ctrl-btn" id="tg-zoom-out" title="Zoom out">−</button>
      <button class="tg-ctrl-btn" id="tg-zoom-fit" title="Fit all" style="font-size:13px">⊙</button>
    </div>
  </div>

  <div id="tg-panel-interactive">
    <div class="tg-interactive-inner" id="tg-interactive-root"></div>
  </div>

  <footer>
    <span>Treage v1.1.0</span>
    <span class="tg-sep">·</span>
    <a href="https://github.com/rseldner/treage" target="_blank" rel="noopener">github.com/rseldner/treage</a>
    <span class="tg-sep">·</span>
    <span>MIT License</span>
  </footer>
</div>
`;

/* ============================================================
   ENGINE
   ============================================================ */

const LAYOUT = {
  nodeHGap: 56, nodeVGap: 64,
  minWidth: 220, maxWidth: 290, minHeight: 72,
  lineHeight: 16, paddingV: 22, charsPerLine: 34,
};

let currentTheme = 'dark';
let treeSvg, treeG, treeZoom, fitView;
const iState = { path: [], choices: [] };

/* ── Palette helpers ── */
function activePalette() {
  return currentTheme === 'light' ? CONFIG.paletteLight : CONFIG.palette;
}

function nodeTypeCfg(typeKey) {
  const t = CONFIG.nodeTypes[typeKey] || CONFIG.nodeTypes.question;
  return { ...t, ...(currentTheme === 'light' ? t.light : t.dark) };
}

function edgeColors() {
  const p = activePalette();
  return { YES: p.edgeYes, NO: p.edgeNo, default: p.edgeDefault };
}

function applyPalette() {
  const r = document.documentElement.style;
  const p = activePalette();
  r.setProperty('--color-bg',      p.bg);
  r.setProperty('--color-surface', p.surface);
  r.setProperty('--color-border',  p.border);
  r.setProperty('--color-text',    p.text);
  r.setProperty('--color-muted',   p.muted);
  r.setProperty('--color-dim',     p.dim);
  r.setProperty('--color-accent',  p.accent);
  r.setProperty('--edge-yes',      p.edgeYes);
  r.setProperty('--edge-no',       p.edgeNo);
  r.setProperty('--grid-line',     p.gridLine);
  r.setProperty('--header-bg',     p.headerBg);
  r.setProperty('--font-body',     CONFIG.fonts.body);
  r.setProperty('--font-mono',     CONFIG.fonts.mono);
}

/* ── Layout ── */
function autoSize(nodeData) {
  if (nodeData.type === 'start') return { w: 140, h: 42 };
  const title = nodeData.title || '', hint = nodeData.hint || '';
  const tl = Math.ceil(title.length / LAYOUT.charsPerLine) || 1;
  const hl = hint ? Math.ceil(hint.length  / LAYOUT.charsPerLine) || 1 : 0;
  const contentH = 20 + (tl * LAYOUT.lineHeight) + (hl * (LAYOUT.lineHeight - 2)) + (hl > 0 ? 8 : 0);
  return { w: LAYOUT.maxWidth, h: Math.max(LAYOUT.minHeight, contentH + LAYOUT.paddingV) };
}

function buildLayout(data) {
  const root = d3.hierarchy(data);
  root.each(d => { const s = autoSize(d.data); d.nodeW = s.w; d.nodeH = s.h; });
  d3.tree().nodeSize([1,1])
    .separation((a,b) => (a.nodeW/2) + (b.nodeW/2) + LAYOUT.nodeHGap)(root);
  const depthMaxH = {};
  root.each(d => { depthMaxH[d.depth] = Math.max(depthMaxH[d.depth] || 0, d.nodeH); });
  const depthY = {}; let cumY = 0;
  const maxDepth = Math.max(...Object.keys(depthMaxH).map(Number));
  for (let i = 0; i <= maxDepth; i++) { depthY[i] = cumY; cumY += (depthMaxH[i] || 72) + LAYOUT.nodeVGap; }
  root.each(d => { d.px = d.x; d.py = depthY[d.depth]; });
  return { nodes: root.descendants(), links: root.links() };
}

/* ── Full tree renderer ── */
function renderFullTree(g, layout) {
  const { nodes, links } = layout;
  const edges = edgeColors(), p = activePalette();

  const svgEl = g.node().closest('svg');
  let defs = d3.select(svgEl).select('defs');
  if (defs.empty()) defs = d3.select(svgEl).append('defs');

  const allLabels = new Set(['YES','NO','default']);
  links.forEach(l => { if (l.target.data.edgeLabel) allLabels.add(l.target.data.edgeLabel); });
  allLabels.forEach(label => {
    const color = edges[label] || edges.default;
    const id    = `tg-arrow-${label.toLowerCase().replace(/[^a-z0-9]/g,'-')}`;
    defs.selectAll(`#${id}`).remove();
    defs.append('marker').attr('id', id).attr('viewBox','0 -4 8 8')
      .attr('refX',7).attr('refY',0).attr('markerWidth',6).attr('markerHeight',6).attr('orient','auto')
      .append('path').attr('d','M0,-4L8,0L0,4').attr('fill',color);
  });

  const edgeG = g.append('g').attr('class','tg-edges');
  links.forEach(lk => {
    const src = lk.source, tgt = lk.target;
    const x1 = src.px, y1 = src.py + src.nodeH, x2 = tgt.px, y2 = tgt.py, midY = (y1+y2)/2;
    const label = tgt.data.edgeLabel || '';
    const color = edges[label] || edges.default;
    const safeId = label.toLowerCase().replace(/[^a-z0-9]/g,'-') || 'default';

    edgeG.append('path')
      .attr('d', `M${x1},${y1} C${x1},${midY} ${x2},${midY} ${x2},${y2}`)
      .attr('fill','none').attr('stroke',color)
      .attr('stroke-width',1.5).attr('stroke-opacity',0.65)
      .attr('marker-end',`url(#tg-arrow-${safeId})`);

    if (label) {
      const lx = x2, ly = midY - 6, tw = label.length * 7 + 10, th = 16;
      edgeG.append('rect').attr('x',lx-tw/2).attr('y',ly-th+4)
        .attr('width',tw).attr('height',th).attr('rx',4).attr('fill',p.bg).attr('opacity',0.92);
      edgeG.append('text').attr('class','tg-edge-label')
        .attr('x',lx).attr('y',ly).attr('text-anchor','middle').attr('fill',color).text(label);
    }
  });

  const nodeG = g.append('g').attr('class','tg-nodes');
  nodes.forEach(d => {
    const data = d.data, typeCfg = nodeTypeCfg(data.type);
    const nw = d.nodeW, nh = d.nodeH, nx = d.px - nw/2, ny = d.py;

    const fo = nodeG.append('foreignObject').attr('x',nx).attr('y',ny).attr('width',nw).attr('height',nh);
    const card = fo.append('xhtml:div')
      .attr('xmlns','http://www.w3.org/1999/xhtml').attr('class','tg-node-card')
      .style('background', typeCfg.bg)
      .style('border',     typeCfg.border || 'none')
      .style('border-left',typeCfg.borderLeft || typeCfg.border || 'none');

    if (data.type === 'start') {
      card.append('xhtml:div').attr('class','tg-card-title')
        .style('color', typeCfg.titleColor).style('font-family', CONFIG.fonts.mono)
        .style('font-size','13px').style('font-weight','600')
        .style('letter-spacing','2px').style('text-transform','uppercase')
        .style('text-align','center').text(data.title);
      return;
    }

    const eb = card.append('xhtml:div').attr('class','tg-card-eyebrow').style('color', typeCfg.eyebrowColor);
    eb.append('xhtml:span').text(data.eyebrow || typeCfg.label || data.type.toUpperCase());
    if (data.isNew) eb.append('xhtml:span').attr('class','tg-new-badge').text('NEW');
    card.append('xhtml:div').attr('class','tg-card-title').style('color', typeCfg.titleColor).text(data.title || '');
    if (data.hint) card.append('xhtml:div').attr('class','tg-card-hint').style('color', typeCfg.hintColor).text(data.hint);
  });
}

function rebuildTree() {
  if (!treeG) return;
  treeG.selectAll('*').remove();
  renderFullTree(treeG, buildLayout(TREE));
}

/* ── Interactive engine ── */
function firstQuestion(node) {
  if (node.type !== 'start') return node;
  return (node.children && node.children[0]) ? node.children[0] : node;
}
function iReset() {
  iState.path    = [ firstQuestion(TREE) ];
  iState.choices = [];
  iRender();
}
function iChoose(child) {
  iState.choices.push({ label: child.edgeLabel || child.type, node: child });
  iState.path.push(child);
  iRender();
}
function iGoTo(index) {
  iState.path    = iState.path.slice(0, index + 1);
  iState.choices = iState.choices.slice(0, index);
  iRender();
}

function iRender() {
  const root = document.getElementById('tg-interactive-root');
  if (!root) return;
  root.innerHTML = '';

  const current   = iState.path[iState.path.length - 1];
  const depth     = iState.path.length;
  const isOutcome = current.type !== 'question' && current.type !== 'start';
  const typeCfg   = nodeTypeCfg(current.type);
  const edges     = edgeColors();
  const p         = activePalette();

  // breadcrumb
  if (iState.choices.length > 0) {
    const bc = document.createElement('div');
    bc.className = 'tg-breadcrumb';
    const s0 = document.createElement('span');
    s0.className = 'tg-crumb-link'; s0.textContent = 'Start';
    s0.onclick = () => iGoTo(0);
    bc.appendChild(s0);
    iState.choices.forEach((c, i) => {
      const sep = document.createElement('span');
      sep.className = 'tg-crumb-sep'; sep.textContent = '›';
      bc.appendChild(sep);
      const lbl = document.createElement('span');
      const isLast = i === iState.choices.length - 1;
      lbl.className = isLast ? 'tg-crumb-current' : 'tg-crumb-link';
      lbl.style.color = edges[c.label] || edges.default;
      if (!isLast) lbl.onclick = () => iGoTo(i + 1);
      lbl.textContent = c.label;
      bc.appendChild(lbl);
    });
    root.appendChild(bc);
  }

  // progress dots
  const pr = document.createElement('div');
  pr.className = 'tg-progress-row';
  const totalDots = Math.max(depth, 4);
  for (let i = 0; i < totalDots; i++) {
    const dot = document.createElement('div');
    dot.className = 'tg-progress-dot';
    dot.style.background = i < depth - 1 ? p.border : i === depth - 1 ? p.accent : p.surface;
    dot.style.transform  = i === depth - 1 ? 'scale(1.5)' : 'scale(1)';
    if (i < depth - 1) dot.onclick = () => iGoTo(i + 1);
    pr.appendChild(dot);
  }
  root.appendChild(pr);

  // card
  const card = document.createElement('div');

  if (!isOutcome) {
    card.className = 'tg-i-card';
    const eyebrow = document.createElement('div');
    eyebrow.className = 'tg-i-step-label'; eyebrow.textContent = current.eyebrow || '';
    if (current.isNew) {
      const badge = document.createElement('span');
      badge.className = 'tg-new-badge'; badge.textContent = 'NEW';
      eyebrow.appendChild(badge);
    }
    card.appendChild(eyebrow);
    const q = document.createElement('div');
    q.className = 'tg-i-question'; q.textContent = current.title;
    card.appendChild(q);
    if (current.hint) {
      const h = document.createElement('div');
      h.className = 'tg-i-hint'; h.textContent = current.hint;
      card.appendChild(h);
    }
    const optRow = document.createElement('div');
    optRow.className = 'tg-options-row';
    (current.children || []).forEach(child => {
      const btn = document.createElement('button');
      const isYes = child.edgeLabel === 'YES', isNo = child.edgeLabel === 'NO';
      btn.className = 'tg-opt-btn ' + (isYes ? 'tg-yes' : isNo ? 'tg-no' : '');
      const icon = document.createElement('span');
      icon.className = 'tg-opt-icon';
      icon.textContent = isYes ? '✓' : isNo ? '✗' : '→';
      btn.appendChild(icon);
      btn.appendChild(document.createTextNode(child.edgeLabel || child.eyebrow || child.type));
      btn.onclick = () => iChoose(child);
      optRow.appendChild(btn);
    });
    card.appendChild(optRow);

  } else {
    card.className = 'tg-outcome-card';
    card.style.background = typeCfg.bg;
    card.style.border     = typeCfg.border || 'none';
    card.style.borderLeft = typeCfg.borderLeft || typeCfg.border || 'none';

    const badge = document.createElement('div');
    badge.className = 'tg-outcome-badge';
    badge.textContent = typeCfg.label || current.type.toUpperCase();
    const accent = typeCfg.accent || CONFIG.nodeTypes[current.type]?.accent;
    badge.style.color = accent; badge.style.background = typeCfg.bg; badge.style.borderColor = accent;
    card.appendChild(badge);

    const ey = document.createElement('div');
    ey.className = 'tg-outcome-eyebrow'; ey.style.color = typeCfg.eyebrowColor;
    ey.textContent = current.eyebrow || typeCfg.label || '';
    card.appendChild(ey);

    const t = document.createElement('div');
    t.className = 'tg-outcome-title'; t.style.color = typeCfg.titleColor;
    t.textContent = current.title;
    card.appendChild(t);

    if (current.hint) {
      const h = document.createElement('div');
      h.className = 'tg-outcome-hint'; h.style.color = typeCfg.hintColor;
      h.textContent = current.hint;
      card.appendChild(h);
    }

    const reset = document.createElement('button');
    reset.className = 'tg-reset-btn'; reset.innerHTML = '↺ Start over';
    reset.onclick = () => iReset();
    card.appendChild(reset);
  }

  root.appendChild(card);

  if (iState.path.length > 1) {
    const back = document.createElement('button');
    back.className = 'tg-back-btn'; back.textContent = '← Back';
    back.onclick = () => iGoTo(iState.path.length - 2);
    root.appendChild(back);
  }
}

/* ── Public API (called from inline onclick handlers) ── */
window.treage = {
  setMode(mode) {
    const isTree = mode === 'tree';
    document.getElementById('tg-panel-tree').classList.toggle('tg-visible', isTree);
    document.getElementById('tg-panel-interactive').classList.toggle('tg-visible', !isTree);
    document.getElementById('tg-btn-tree').classList.toggle('active', isTree);
    document.getElementById('tg-btn-interactive').classList.toggle('active', !isTree);
    document.getElementById('tg-header-sub').textContent = isTree
      ? CONFIG.subtitle + ' — Scroll to zoom · Drag to pan.'
      : CONFIG.subtitle;
    if (isTree && fitView) setTimeout(() => fitView(300), 50);
  },

  toggleTheme() {
    currentTheme = currentTheme === 'dark' ? 'light' : 'dark';
    document.body.classList.toggle('tg-light', currentTheme === 'light');
    applyPalette();
    rebuildTree();
    iRender();
    try { localStorage.setItem('treage-theme', currentTheme); } catch(e) {}
  },
};

/* ── Init ── */
function init() {
  /* Inject styles and DOM shell — must be first */
  document.documentElement.lang = 'en';
  document.head.insertAdjacentHTML('beforeend', TREAGE_STYLES);
  document.body.innerHTML = TREAGE_BODY;

  // Restore saved preference
  try {
    if (localStorage.getItem('treage-theme') === 'light') {
      currentTheme = 'light';
      document.body.classList.add('tg-light');
    }
  } catch(e) {}

  applyPalette();

  document.getElementById('tg-header-title').textContent = CONFIG.title;
  document.getElementById('tg-header-sub').textContent   = CONFIG.subtitle + ' — Scroll to zoom · Drag to pan.';
  document.getElementById('tg-header-icon').innerHTML    = CONFIG.icon || '';
  document.title = CONFIG.title;

  // Legend
  const legendEl = document.getElementById('tg-legend');
  Object.values(CONFIG.nodeTypes).forEach(t => {
    if (!t.legendLabel) return;
    const item = document.createElement('div');
    item.className = 'tg-legend-item';
    item.innerHTML = `<span class="tg-legend-dot" style="background:${t.accent}"></span>${t.legendLabel}`;
    legendEl.appendChild(item);
  });

  // Full tree
  const container = document.getElementById('tg-canvas');
  treeSvg = d3.select(container).append('svg').attr('width','100%').attr('height','100%');
  treeSvg.append('defs');
  treeG = treeSvg.append('g').attr('class','tg-main-g');

  treeZoom = d3.zoom().scaleExtent([0.08, 2.5])
    .on('zoom', e => treeG.attr('transform', e.transform));
  treeSvg.call(treeZoom);

  fitView = function(duration = 600) {
    const bounds = treeG.node().getBBox();
    if (!bounds.width || !bounds.height) return;
    const cw = container.clientWidth, ch = container.clientHeight, pad = 48;
    const scale = Math.min((cw-pad*2)/bounds.width, (ch-pad*2)/bounds.height, 1.0);
    const tx = cw/2 - scale*(bounds.x + bounds.width/2);
    const ty = pad + (ch-pad*2 - scale*bounds.height)/2 - scale*bounds.y;
    treeSvg.transition().duration(duration)
      .call(treeZoom.transform, d3.zoomIdentity.translate(tx,ty).scale(scale));
  };

  document.getElementById('tg-zoom-in') .onclick = () => treeSvg.transition().duration(280).call(treeZoom.scaleBy, 1.3);
  document.getElementById('tg-zoom-out').onclick = () => treeSvg.transition().duration(280).call(treeZoom.scaleBy, 0.77);
  document.getElementById('tg-zoom-fit').onclick = () => fitView(400);

  renderFullTree(treeG, buildLayout(TREE));
  setTimeout(() => fitView(500), 100);
  window.addEventListener('resize', () => fitView(300));

  iReset();
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', init);
} else {
  init();
}

})();
