/* ============================================================
   TREAGE v1.2.3 — Interactive Decision Tree Framework Engine
   https://github.com/rseldner/treage

   Load AFTER d3 and AFTER your CONFIG + TREE definitions.
   This file owns: DOM shell, all CSS, layout, rendering,
   interactive mode, theme toggle, zoom/pan, and init.

   You supply (in your consumer file, before this script):
     const CONFIG = { ... };   // meta, palettes, nodeTypes
     const TREE   = { ... };   // your tree data

   DO NOT EDIT THIS FILE to customise your tree.
   Edit CONFIG and TREE in your own file instead.
   To upgrade: replace this file with the new version.

   v1.2.3 — feat: time-based isNew badge via isNewUntil date field.
            feat: configurable edge label colors via CONFIG.edgeLabels.
            fix: playground shared URL renders without page refresh.
   v1.2.2 — feat: SVG export button in tree view controls (download current tree as SVG).
            fix: header overflow on narrow viewports — mobile-responsive layout
             with collapsible subtitle and legend (Info toggle, collapsed by default).
   v1.2.1 — fix: single-child nodes no longer treated as terminal outcomes
             fix: auto-pan biased upward so child nodes remain visible
             fix: header text truncates with ellipsis instead of overflowing.
   v1.2.0 — tree view walk: click edge labels to advance path,
             active path highlight, auto-pan to next node,
             click Start node to reset walk.
             Walk mode: progressive top-down walk panel,
             ghost stubs for unchosen siblings,
             reset bug fix (choices.length guard).
   ============================================================ */

(function () {
'use strict';

const TREAGE_STYLES = `
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&family=IBM+Plex+Sans:wght@300;400;500;600&display=swap" rel="stylesheet">
<style id="treage-styles">
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html, body { width: 100%; height: 100%; overflow: hidden; }
body {
  font-family: var(--font-body, 'IBM Plex Sans', sans-serif);
  background: var(--color-bg, #0d0f14);
  color: var(--color-text, #e8eaf0);
  display: flex; flex-direction: column;
  transition: background 0.25s ease, color 0.25s ease;
}
body::before {
  content: '';
  position: fixed; inset: 0;
  background-image:
    linear-gradient(var(--grid-line, rgba(255,255,255,0.018)) 1px, transparent 1px),
    linear-gradient(90deg, var(--grid-line, rgba(255,255,255,0.018)) 1px, transparent 1px);
  background-size: 40px 40px;
  pointer-events: none; z-index: 0;
  transition: opacity 0.25s ease;
}
#treage-app { position: relative; z-index: 1; display: flex; flex-direction: column; height: 100%; overflow: hidden; }
/* ── Header ── */
header {
  display: flex; align-items: center; gap: 16px;
  padding: 0 28px; height: 60px;
  border-bottom: 1px solid var(--color-border, #252a38);
  flex-shrink: 0;
  background: var(--header-bg, rgba(13,15,20,0.95));
  backdrop-filter: blur(10px);
  position: relative; z-index: 2;
  transition: background 0.25s ease, border-color 0.25s ease;
}
.tg-header-icon { flex-shrink: 0; }
.tg-header-text { min-width: 0; overflow: hidden; }
.tg-header-text h1 { font-size: 17px; font-weight: 600; letter-spacing: -0.2px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.tg-header-text p  { font-size: 12px; color: var(--color-muted, #7a8099); font-weight: 300; margin-top: 2px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
/* ── Legend toggle button (mobile only) ── */
.tg-legend-toggle {
  display: none; align-items: center; gap: 5px;
  background: none; border: none; cursor: pointer;
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 10px; font-weight: 600; letter-spacing: 0.5px; text-transform: uppercase;
  color: var(--color-muted, #7a8099); padding: 0; flex-shrink: 0;
  transition: color 0.18s;
}
.tg-legend-toggle:hover { color: var(--color-text, #e8eaf0); }
.tg-legend-toggle svg { width: 12px; height: 12px; transition: transform 0.2s ease; }
.tg-legend-toggle.tg-expanded svg { transform: rotate(180deg); }
/* ── Collapsible secondary row ── */
.tg-header-secondary {
  display: none; /* hidden on desktop — shown via @media below */
  width: 100%; padding: 0 28px 10px;
  overflow: hidden;
  transition: max-height 0.25s ease, opacity 0.2s ease;
}
.tg-header-secondary.tg-collapsed { max-height: 0; opacity: 0; pointer-events: none; padding-bottom: 0; }
.tg-header-secondary.tg-expanded  { max-height: 200px; opacity: 1; pointer-events: auto; }
.tg-secondary-sub {
  font-size: 11px; color: var(--color-muted, #7a8099); font-weight: 300;
  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
  margin-bottom: 8px;
}
/* ── Responsive: mobile header ── */
@media (max-width: 768px) {
  header {
    height: auto; flex-wrap: wrap;
    padding: 10px 16px 10px;
    gap: 10px;
  }
  .tg-header-text p { display: none; } /* moved to secondary row */
  .tg-legend { display: none !important; } /* moved to secondary row */
  .tg-legend-toggle { display: flex; }
  .tg-header-secondary { display: block; padding: 0 16px 10px; }
  .tg-mode-toggle { margin-left: auto; }
  .tg-github-link { display: none; }
}
/* ── Mode toggle ── */
.tg-mode-toggle {
  display: flex;
  background: var(--color-surface, #13161e);
  border: 1px solid var(--color-border, #252a38);
  border-radius: 8px; padding: 3px; gap: 3px;
  margin-left: 24px; flex-shrink: 0;
  transition: background 0.25s ease, border-color 0.25s ease;
}
.tg-mode-btn {
  padding: 5px 14px; border-radius: 5px; border: none;
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 11px; font-weight: 600; letter-spacing: 0.5px;
  text-transform: uppercase; cursor: pointer; transition: all 0.18s;
  color: var(--color-dim, #4a5068); background: transparent;
}
.tg-mode-btn.active { background: var(--color-border, #252a38); color: var(--color-text, #e8eaf0); }
.tg-mode-btn:not(.active):hover { color: var(--color-muted, #7a8099); }
/* ── Theme toggle ── */
.tg-theme-btn {
  width: 34px; height: 34px;
  display: flex; align-items: center; justify-content: center;
  background: var(--color-surface, #13161e);
  border: 1px solid var(--color-border, #252a38);
  border-radius: 8px; cursor: pointer; flex-shrink: 0;
  transition: all 0.18s; color: var(--color-muted, #7a8099); margin-left: 4px;
}
.tg-theme-btn:hover { border-color: var(--color-accent, #00bfb3); color: var(--color-accent, #00bfb3); }
.tg-theme-btn svg { width: 16px; height: 16px; transition: transform 0.35s ease; }
.tg-theme-btn:hover svg { transform: rotate(20deg); }
.tg-icon-moon { display: block; }
.tg-icon-sun  { display: none;  }
body.tg-light .tg-icon-moon { display: none;  }
body.tg-light .tg-icon-sun  { display: block; }
/* ── Legend ── */
.tg-legend { margin-left: auto; display: flex; gap: 18px; flex-wrap: wrap; align-items: center; }
.tg-legend-item {
  display: flex; align-items: center; gap: 6px;
  font-size: 10.5px; font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  color: var(--color-muted, #7a8099); text-transform: uppercase; letter-spacing: 0.5px;
}
.tg-legend-dot { width: 9px; height: 9px; border-radius: 50%; flex-shrink: 0; }
/* mobile legend lives inside .tg-header-secondary */
.tg-legend-mobile { display: flex; flex-wrap: wrap; gap: 12px; align-items: center; margin-top: 4px; }
/* ── GitHub link ── */
.tg-github-link {
  display: flex; align-items: center; gap: 7px;
  color: var(--color-muted, #7a8099); text-decoration: none;
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 11px; font-weight: 600; letter-spacing: 0.5px; text-transform: uppercase;
  padding: 6px 12px;
  border: 1px solid var(--color-border, #252a38); border-radius: 7px;
  transition: all 0.18s; flex-shrink: 0; margin-left: 12px;
}
.tg-github-link:hover { color: var(--color-text, #e8eaf0); border-color: var(--color-accent, #00bfb3); }
/* ── Panels ── */
#tg-panel-tree, #tg-panel-interactive {
  flex: 1; overflow: hidden; display: none; flex-direction: column;
}
#tg-panel-tree.tg-visible { display: flex; }
#tg-panel-interactive.tg-visible { display: flex; overflow-y: auto; }
/* ── Full-tree canvas ── */
#tg-canvas { flex: 1; overflow: hidden; }
#tg-canvas svg { width: 100%; height: 100%; }
.tg-controls {
  position: absolute; bottom: 20px; right: 20px;
  display: flex; flex-direction: column; gap: 6px; z-index: 10;
}
.tg-ctrl-btn {
  width: 36px; height: 36px;
  background: var(--color-surface, #1a1e2a);
  border: 1px solid var(--color-dim, #3a4158);
  border-radius: 8px; color: var(--color-muted, #7a8099);
  font-size: 18px; cursor: pointer;
  display: flex; align-items: center; justify-content: center;
  transition: all 0.2s; font-family: monospace; line-height: 1; user-select: none;
}
.tg-ctrl-btn:hover { color: var(--color-text, #e8eaf0); border-color: var(--color-accent, #00bfb3); }
/* ── Node cards (full-tree SVG) ── */
.tg-node-card {
  width: 100%; height: 100%; border-radius: 10px; padding: 11px 14px;
  display: flex; flex-direction: column; justify-content: center; overflow: hidden;
  box-sizing: border-box;
}
.tg-card-eyebrow {
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 9.5px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px;
  margin-bottom: 5px; display: flex; align-items: center; gap: 5px;
}
.tg-new-badge {
  background: rgba(254,197,20,0.15); color: #fec514;
  border: 1px solid rgba(254,197,20,0.3);
  border-radius: 4px; font-size: 8px; padding: 1px 4px; letter-spacing: 0.5px;
}
.tg-card-title { font-size: 12px; font-weight: 500; line-height: 1.45; }
.tg-card-hint  { font-size: 10.5px; font-weight: 300; font-style: italic; margin-top: 5px; line-height: 1.4; }
.tg-edge-label {
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 10px; font-weight: 600; letter-spacing: 0.8px;
  text-transform: uppercase; pointer-events: none;
}
/* ── Interactive view ── */
.tg-interactive-inner { max-width: 680px; width: 100%; margin: 0 auto; padding: 32px 24px 48px; }
.tg-progress-row { display: flex; gap: 7px; align-items: center; margin-bottom: 24px; }
.tg-progress-dot { width: 8px; height: 8px; border-radius: 50%; transition: all 0.2s ease; cursor: pointer; }
.tg-breadcrumb {
  display: flex; flex-wrap: wrap; align-items: center;
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 11px; color: var(--color-dim, #4a5068); margin-bottom: 20px; gap: 2px;
}
.tg-crumb-link { cursor: pointer; text-decoration: underline; text-decoration-color: var(--color-border, #252a38); color: var(--color-dim, #4a5068); }
.tg-crumb-link:hover { color: var(--color-accent, #00bfb3); }
.tg-crumb-sep { color: var(--color-border, #252a38); margin: 0 4px; }
.tg-crumb-current { color: var(--color-accent, #00bfb3); }
.tg-i-card {
  background: var(--color-surface, #13161e);
  border: 1px solid var(--color-border, #1a1e2a);
  border-radius: 10px; padding: 28px 28px 24px;
  box-shadow: 0 4px 40px rgba(0,0,0,0.35);
  transition: background 0.25s ease, border-color 0.25s ease, box-shadow 0.25s ease;
}
.tg-i-step-label {
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px;
  color: var(--color-dim, #4a5068); margin-bottom: 10px;
  display: flex; align-items: center; gap: 7px;
}
.tg-i-question { font-size: 18px; font-weight: 500; color: var(--color-text, #e8eaf0); line-height: 1.5; margin: 0 0 10px; }
.tg-i-hint     { font-size: 12px; font-weight: 300; font-style: italic; color: var(--color-dim, #4a5068); line-height: 1.5; margin: 0 0 24px; }
.tg-options-row { display: flex; gap: 12px; flex-wrap: wrap; }
.tg-opt-btn {
  flex: 1; min-width: 120px; border-radius: 8px; padding: 14px 20px;
  font-size: 15px; font-weight: 600; font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  letter-spacing: 0.5px; cursor: pointer;
  display: flex; align-items: center; justify-content: center; gap: 8px;
  transition: all 0.15s ease;
  border: 1px solid var(--color-border, #252a38);
  background: var(--color-surface, #13161e); color: var(--color-text, #e8eaf0);
}
.tg-opt-btn.tg-yes:hover { background: rgba(61,214,140,0.07); border-color: var(--edge-yes, #3dd68c); color: var(--edge-yes, #3dd68c); transform: translateY(-2px); }
.tg-opt-btn.tg-no:hover  { background: rgba(255,107,107,0.07); border-color: var(--edge-no,  #ff6b6b); color: var(--edge-no,  #ff6b6b); transform: translateY(-2px); }
.tg-opt-icon { font-size: 15px; color: var(--color-dim, #3a4158); transition: color 0.15s; }
.tg-opt-btn.tg-yes:hover .tg-opt-icon { color: var(--edge-yes, #3dd68c); }
.tg-opt-btn.tg-no:hover  .tg-opt-icon { color: var(--edge-no,  #ff6b6b); }
.tg-outcome-card { border-radius: 10px; padding: 28px 28px 24px; box-shadow: 0 4px 40px rgba(0,0,0,0.35); }
.tg-outcome-badge {
  display: inline-block; font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px;
  padding: 3px 10px; border-radius: 4px; border: 1px solid; margin-bottom: 14px;
}
.tg-outcome-eyebrow {
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px;
  margin-bottom: 8px; display: flex; align-items: center; gap: 7px;
}
.tg-outcome-title { font-size: 15px; font-weight: 500; line-height: 1.55; margin: 0 0 14px; }
.tg-outcome-hint  { font-size: 12px; font-weight: 300; font-style: italic; line-height: 1.5; opacity: 0.65; }
.tg-back-btn {
  background: none; border: none; color: var(--color-dim, #4a5068);
  font-size: 13px; cursor: pointer; font-family: inherit;
  margin-top: 18px; padding: 0; transition: color 0.15s;
}
.tg-back-btn:hover { color: var(--color-accent, #00bfb3); }
.tg-reset-btn {
  display: inline-flex; align-items: center; gap: 6px;
  background: none; border: 1px solid var(--color-border, #252a38);
  border-radius: 6px; padding: 8px 14px; color: var(--color-muted, #7a8099);
  font-size: 12px; font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  text-transform: uppercase; letter-spacing: 0.5px;
  cursor: pointer; margin-top: 20px; transition: all 0.15s;
}
.tg-reset-btn:hover { color: var(--color-accent, #00bfb3); border-color: var(--color-accent, #00bfb3); }
/* ── Walk mode ── */
#tg-panel-walk { flex: 1; overflow-y: auto; display: none; flex-direction: column; }
#tg-panel-walk.tg-visible { display: flex; }
.tg-walk-inner { max-width: 560px; width: 100%; margin: 0 auto; padding: 28px 24px 56px; display: flex; flex-direction: column; }
.tg-walk-node {
  border: 1px solid var(--color-border, #252a38);
  border-radius: 10px; padding: 14px 16px;
  background: var(--color-surface, #13161e);
  opacity: 0.72;
  transition: opacity 0.2s;
  cursor: pointer;
}
.tg-walk-node:hover { opacity: 0.88; }
.tg-walk-node.tg-walk-active {
  opacity: 1;
  border-color: var(--color-accent, #00bfb3);
  border-width: 1.5px;
  cursor: default;
}
.tg-walk-node .tg-walk-ey {
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 9.5px; font-weight: 600; text-transform: uppercase;
  letter-spacing: 1px; color: var(--color-dim, #4a5068); margin-bottom: 5px;
  display: flex; align-items: center; gap: 6px;
}
.tg-walk-node .tg-walk-title { font-size: 13px; font-weight: 500; line-height: 1.5; color: var(--color-text, #e8eaf0); }
.tg-walk-node .tg-walk-hint { font-size: 11px; font-weight: 300; font-style: italic; color: var(--color-muted, #7a8099); margin-top: 6px; line-height: 1.45; }
.tg-walk-connector { display: flex; align-items: center; gap: 8px; padding: 3px 0; min-height: 22px; }
.tg-walk-vline { width: 1.5px; height: 18px; background: var(--color-border, #252a38); margin-left: 16px; flex-shrink: 0; }
.tg-walk-epill {
  display: inline-flex; align-items: center; height: 17px; padding: 0 8px;
  border-radius: 9px; font-size: 9px; font-weight: 700;
  font-family: var(--font-mono, 'IBM Plex Mono', monospace); letter-spacing: 0.6px;
}
.tg-walk-epill.tg-yes { background: var(--edge-yes, #3dd68c); color: #071a0c; }
.tg-walk-epill.tg-no  { background: var(--edge-no,  #ff6b6b); color: #1a0505; }
.tg-walk-epill.tg-def { background: var(--color-border, #252a38); color: var(--color-muted, #7a8099); }
.tg-walk-epill.tg-ghost { background: transparent; border: 1px solid var(--color-border, #252a38); color: var(--color-dim, #4a5068); opacity: 0.45; }
.tg-walk-ghost {
  border: 1px dashed var(--color-border, #252a38); border-radius: 10px;
  padding: 8px 16px; opacity: 0.32;
  display: flex; align-items: center; justify-content: space-between;
}
.tg-walk-ghost .tg-walk-gt {
  font-size: 11px; font-style: italic; color: var(--color-muted, #7a8099);
  white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 80%;
}
.tg-walk-ghost .tg-walk-gc {
  font-size: 9px; font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  color: var(--color-dim, #4a5068); flex-shrink: 0; margin-left: 8px;
}
.tg-walk-choices-label {
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 9.5px; font-weight: 600; text-transform: uppercase;
  letter-spacing: 1px; color: var(--color-dim, #4a5068);
  margin: 16px 0 8px;
}
.tg-walk-choices { display: flex; flex-direction: column; gap: 7px; }
.tg-walk-choice {
  border: 1px solid var(--color-border, #252a38);
  border-radius: 10px; padding: 10px 16px;
  background: var(--color-surface, #13161e);
  cursor: pointer; display: flex; align-items: center; gap: 12px;
  transition: all 0.15s;
}
.tg-walk-choice:hover { border-color: var(--color-muted, #7a8099); background: rgba(255,255,255,0.03); transform: translateY(-1px); }
.tg-walk-choice.tg-yes:hover { border-color: var(--edge-yes, #3dd68c); background: rgba(61,214,140,0.05); }
.tg-walk-choice.tg-no:hover  { border-color: var(--edge-no,  #ff6b6b); background: rgba(255,107,107,0.05); }
.tg-walk-choice .tg-walk-cl {
  font-size: 11px; font-weight: 700; text-transform: uppercase;
  letter-spacing: 0.8px; font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  flex-shrink: 0;
}
.tg-walk-choice.tg-yes .tg-walk-cl { color: var(--edge-yes, #3dd68c); }
.tg-walk-choice.tg-no  .tg-walk-cl { color: var(--edge-no,  #ff6b6b); }
.tg-walk-choice.tg-def .tg-walk-cl { color: var(--color-muted, #7a8099); }
.tg-walk-choice .tg-walk-ctext { display: flex; flex-direction: column; gap: 3px; }
.tg-walk-choice .tg-walk-cey {
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 9px; font-weight: 600; text-transform: uppercase;
  letter-spacing: 0.8px; color: var(--color-dim, #4a5068);
}
.tg-walk-choice .tg-walk-ctitle { font-size: 12px; font-weight: 500; color: var(--color-text, #e8eaf0); line-height: 1.4; }
.tg-walk-outcome { border-radius: 10px; padding: 20px 18px; margin-top: 4px; }
/* ── Footer ── */
footer {
  flex-shrink: 0; display: flex; align-items: center; justify-content: center; gap: 16px;
  height: 36px; border-top: 1px solid var(--color-border, #252a38);
  background: var(--header-bg, rgba(13,15,20,0.95));
  font-family: var(--font-mono, 'IBM Plex Mono', monospace);
  font-size: 10px; color: var(--color-dim, #4a5068); letter-spacing: 0.5px;
  position: relative; z-index: 2;
  transition: background 0.25s ease, border-color 0.25s ease;
}
footer a { color: var(--color-dim, #4a5068); text-decoration: none; transition: color 0.15s; }
footer a:hover { color: var(--color-accent, #00bfb3); }
footer .tg-sep { color: var(--color-border, #252a38); }
</style>
`;

const TREAGE_BODY = `
<div id="treage-app">
  <header>
    <div class="tg-header-icon" id="tg-header-icon"></div>
    <div class="tg-header-text">
      <h1 id="tg-header-title"></h1>
      <p id="tg-header-sub"></p>
    </div>
    <div class="tg-mode-toggle">
      <button class="tg-mode-btn active" id="tg-btn-tree"        onclick="treage.setMode('tree')">Full Tree</button>
      <button class="tg-mode-btn"        id="tg-btn-walk"        onclick="treage.setMode('walk')">Walk</button>
      <button class="tg-mode-btn"        id="tg-btn-interactive" onclick="treage.setMode('interactive')">Interactive</button>
    </div>
    <button class="tg-theme-btn" id="tg-theme-toggle" title="Toggle light / dark mode" onclick="treage.toggleTheme()">
      <svg class="tg-icon-moon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/>
      </svg>
      <svg class="tg-icon-sun" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <circle cx="12" cy="12" r="5"/>
        <line x1="12" y1="1"  x2="12" y2="3"/>  <line x1="12" y1="21" x2="12" y2="23"/>
        <line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/> <line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/>
        <line x1="1" y1="12" x2="3" y2="12"/>   <line x1="21" y1="12" x2="23" y2="12"/>
        <line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/> <line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/>
      </svg>
    </button>
    <button class="tg-legend-toggle tg-collapsed" id="tg-legend-toggle" onclick="treage.toggleLegend()">
      Info
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
        <polyline points="6 9 12 15 18 9"/>
      </svg>
    </button>
    <div class="tg-legend" id="tg-legend"></div>
    <a class="tg-github-link" href="https://github.com/rseldner/treage" target="_blank" rel="noopener">
      <svg width="15" height="15" viewBox="0 0 24 24" fill="currentColor">
        <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0 0 24 12c0-6.63-5.37-12-12-12z"/>
      </svg>
      GitHub
    </a>
  </header>
  <div class="tg-header-secondary tg-collapsed" id="tg-header-secondary">
    <div class="tg-secondary-sub" id="tg-secondary-sub"></div>
    <div class="tg-legend-mobile" id="tg-legend-mobile"></div>
  </div>

  <div id="tg-panel-tree" class="tg-visible">
    <div id="tg-canvas"></div>
    <div class="tg-controls">
      <button class="tg-ctrl-btn" id="tg-zoom-in"  title="Zoom in">+</button>
      <button class="tg-ctrl-btn" id="tg-zoom-out" title="Zoom out">−</button>
      <button class="tg-ctrl-btn" id="tg-zoom-fit" title="Fit all" style="font-size:13px">⊙</button>
      <button class="tg-ctrl-btn" id="tg-export-png" title="Export as SVG">
        <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
          <polyline points="7 10 12 15 17 10"/>
          <line x1="12" y1="15" x2="12" y2="3"/>
        </svg>
      </button>
    </div>
  </div>

  <div id="tg-panel-walk">
    <div class="tg-walk-inner" id="tg-walk-root"></div>
  </div>

  <div id="tg-panel-interactive">
    <div class="tg-interactive-inner" id="tg-interactive-root"></div>
  </div>

  <footer>
    <span>Treage v1.2.3</span>
    <span class="tg-sep">·</span>
    <a href="https://github.com/rseldner/treage" target="_blank" rel="noopener">github.com/rseldner/treage</a>
    <span class="tg-sep">·</span>
    <span>MIT License</span>
  </footer>
</div>
`;

/* ============================================================
   ENGINE
   ============================================================ */

const LAYOUT = {
  nodeHGap: 56, nodeVGap: 64,
  minWidth: 220, maxWidth: 290, minHeight: 72,
  lineHeight: 16, paddingV: 22, charsPerLine: 34,
};

let currentTheme = 'dark';
let treeSvg, treeG, treeZoom, fitView;
let treeLayout = null;   // cached layout for highlight/pan after initial render
let container  = null;   // cached canvas container
const iState = { path: [], choices: [] };

/* ── Palette helpers ── */
function activePalette() {
  return currentTheme === 'light' ? CONFIG.paletteLight : CONFIG.palette;
}

function isNodeNew(data) {
  if (data.isNewUntil) return new Date() < new Date(data.isNewUntil);
  return !!data.isNew;
}

function nodeTypeCfg(typeKey) {
  const t = CONFIG.nodeTypes[typeKey] || CONFIG.nodeTypes.question;
  return { ...t, ...(currentTheme === 'light' ? t.light : t.dark) };
}

function edgeColors() {
  const p = activePalette();
  const base = { YES: p.edgeYes, NO: p.edgeNo, default: p.edgeDefault };
  return CONFIG.edgeLabels ? { ...base, ...CONFIG.edgeLabels } : base;
}

function applyPalette() {
  const r = document.documentElement.style;
  const p = activePalette();
  r.setProperty('--color-bg',      p.bg);
  r.setProperty('--color-surface', p.surface);
  r.setProperty('--color-border',  p.border);
  r.setProperty('--color-text',    p.text);
  r.setProperty('--color-muted',   p.muted);
  r.setProperty('--color-dim',     p.dim);
  r.setProperty('--color-accent',  p.accent);
  r.setProperty('--edge-yes',      p.edgeYes);
  r.setProperty('--edge-no',       p.edgeNo);
  r.setProperty('--grid-line',     p.gridLine);
  r.setProperty('--header-bg',     p.headerBg);
  r.setProperty('--font-body',     CONFIG.fonts.body);
  r.setProperty('--font-mono',     CONFIG.fonts.mono);
}

/* ── Layout ── */
function autoSize(nodeData) {
  if (nodeData.type === 'start') {
    // uppercase + letter-spacing:2px makes chars render ~13px wide, plus generous padding
    const tw = Math.max(160, (nodeData.title || 'Start').length * 13 + 48);
    return { w: Math.min(tw, LAYOUT.maxWidth), h: 46 };
  }
  const title = nodeData.title || '', hint = nodeData.hint || '';
  const tl = Math.ceil(title.length / LAYOUT.charsPerLine) || 1;
  const hl = hint ? Math.ceil(hint.length  / LAYOUT.charsPerLine) || 1 : 0;
  const contentH = 20 + (tl * LAYOUT.lineHeight) + (hl * (LAYOUT.lineHeight - 2)) + (hl > 0 ? 8 : 0);
  return { w: LAYOUT.maxWidth, h: Math.max(LAYOUT.minHeight, contentH + LAYOUT.paddingV) };
}

function buildLayout(data) {
  const root = d3.hierarchy(data);
  root.each(d => { const s = autoSize(d.data); d.nodeW = s.w; d.nodeH = s.h; });
  d3.tree().nodeSize([1,1])
    .separation((a,b) => (a.nodeW/2) + (b.nodeW/2) + LAYOUT.nodeHGap)(root);
  const depthMaxH = {};
  root.each(d => { depthMaxH[d.depth] = Math.max(depthMaxH[d.depth] || 0, d.nodeH); });
  const depthY = {}; let cumY = 0;
  const maxDepth = Math.max(...Object.keys(depthMaxH).map(Number));
  for (let i = 0; i <= maxDepth; i++) { depthY[i] = cumY; cumY += (depthMaxH[i] || 72) + LAYOUT.nodeVGap; }
  root.each(d => { d.px = d.x; d.py = depthY[d.depth]; });
  return { nodes: root.descendants(), links: root.links() };
}

/* ── Tree walk: path highlighting ── */
function activePathIds() {
  // Returns a Set of node IDs that are on the current walk path.
  // iState.path holds node data objects; collect their IDs.
  const ids = new Set();
  ids.add(TREE.id); // start node always active
  iState.path.forEach(n => ids.add(n.id));
  return ids;
}

function highlightActivePath() {
  if (!treeG || !treeLayout) return;
  const pathIds = activePathIds();
  const hasWalk = iState.choices.length > 0;

  // Edges: active path = full opacity + thicker; others dim
  treeG.selectAll('.tg-walk-edge').each(function(d) {
    const onPath = pathIds.has(d.target.data.id) && pathIds.has(d.source.data.id);
    d3.select(this)
      .attr('stroke-opacity', hasWalk ? (onPath ? 1.0 : 0.12) : 0.65)
      .attr('stroke-width',   onPath  ? 2.5 : 1.5);
  });

  // Edge label hit areas + text: dim off-path
  treeG.selectAll('.tg-walk-label-group').each(function(d) {
    const onPath = pathIds.has(d.target.data.id) && pathIds.has(d.source.data.id);
    d3.select(this).attr('opacity', hasWalk ? (onPath ? 1.0 : 0.15) : 1.0);
  });

  // Nodes: active path = full; others dim
  treeG.selectAll('.tg-tree-node').each(function(d) {
    const onPath = pathIds.has(d.data.id);
    d3.select(this).attr('opacity', hasWalk ? (onPath ? 1.0 : 0.18) : 1.0);
  });
}

/* ── Tree walk: pan to a layout node ── */
function panToNode(d, duration) {
  if (!treeSvg || !treeZoom || !container) return;
  const dur = duration !== undefined ? duration : 450;
  const t = d3.zoomTransform(treeSvg.node());
  const targetX = d.px;
  const targetY = d.py + d.nodeH / 2;
  treeSvg.transition().duration(dur)
    .call(treeZoom.translateTo, targetX, targetY);
}

/* ── Tree walk: advance from an edge click ── */
function treeWalkAdvance(targetNode, layoutNode) {
  // Push onto shared iState
  iState.choices.push({ label: targetNode.edgeLabel || targetNode.type, node: targetNode });
  iState.path.push(targetNode);
  highlightActivePath();
  panToNode(layoutNode);
}

/* ── Tree walk: reset ── */
function treeWalkReset() {
  iState.path    = [];
  iState.choices = [];
  highlightActivePath();
  if (treeLayout) {
    const startNode = treeLayout.nodes.find(n => n.data.id === TREE.id);
    if (startNode) panToNode(startNode, 400);
  }
  iReset();
}

/* ── Full tree renderer ── */
function renderFullTree(g, layout) {
  const { nodes, links } = layout;
  const edges = edgeColors(), p = activePalette();

  const svgEl = g.node().closest('svg');
  let defs = d3.select(svgEl).select('defs');
  if (defs.empty()) defs = d3.select(svgEl).append('defs');

  const allLabels = new Set(['YES','NO','default']);
  links.forEach(l => { if (l.target.data.edgeLabel) allLabels.add(l.target.data.edgeLabel); });
  allLabels.forEach(label => {
    const color = edges[label] || edges.default;
    const id    = `tg-arrow-${label.toLowerCase().replace(/[^a-z0-9]/g,'-')}`;
    defs.selectAll(`#${id}`).remove();
    defs.append('marker').attr('id', id).attr('viewBox','0 -4 8 8')
      .attr('refX',7).attr('refY',0).attr('markerWidth',6).attr('markerHeight',6).attr('orient','auto')
      .append('path').attr('d','M0,-4L8,0L0,4').attr('fill',color);
  });

  const edgeG = g.append('g').attr('class','tg-edges');
  links.forEach(lk => {
    const src = lk.source, tgt = lk.target;
    const x1 = src.px, y1 = src.py + src.nodeH, x2 = tgt.px, y2 = tgt.py, midY = (y1+y2)/2;
    const label = tgt.data.edgeLabel || '';
    const color = edges[label] || edges.default;
    const safeId = label.toLowerCase().replace(/[^a-z0-9]/g,'-') || 'default';

    // Edge path — tagged for walk highlighting
    edgeG.append('path')
      .datum(lk)
      .attr('class', 'tg-walk-edge')
      .attr('d', `M${x1},${y1} C${x1},${midY} ${x2},${midY} ${x2},${y2}`)
      .attr('fill','none').attr('stroke',color)
      .attr('stroke-width',1.5).attr('stroke-opacity',0.65)
      .attr('marker-end',`url(#tg-arrow-${safeId})`);

    if (label) {
      const lx = x2, ly = midY - 6, tw = label.length * 7 + 18, th = 18;

      // Wrap label elements in a group bound to the link datum — used for dimming + click
      const labelG = edgeG.append('g')
        .datum(lk)
        .attr('class', 'tg-walk-label-group')
        .style('cursor', 'pointer');

      // Invisible hit area (larger than the visible pill for easier clicking)
      labelG.append('rect')
        .attr('x', lx - tw/2 - 4).attr('y', ly - th + 1)
        .attr('width', tw + 8).attr('height', th + 4)
        .attr('rx', 5).attr('fill', 'transparent');

      // Visible pill background
      labelG.append('rect')
        .attr('x', lx - tw/2).attr('y', ly - th + 4)
        .attr('width', tw).attr('height', th)
        .attr('rx', 4).attr('fill', p.bg).attr('opacity', 0.92);

      // Label text
      labelG.append('text')
        .attr('class', 'tg-edge-label')
        .attr('x', lx).attr('y', ly)
        .attr('text-anchor', 'middle').attr('fill', color)
        .style('pointer-events', 'none')
        .text(label);

      // Hover: brighten pill on mouseenter, restore on mouseleave
      labelG
        .on('mouseenter', function() {
          d3.select(this).selectAll('rect').filter((d,i) => i === 1)
            .attr('opacity', 1.0);
          d3.select(this).selectAll('text')
            .style('filter', 'brightness(1.3)');
        })
        .on('mouseleave', function() {
          d3.select(this).selectAll('rect').filter((d,i) => i === 1)
            .attr('opacity', 0.92);
          d3.select(this).selectAll('text')
            .style('filter', null);
        })
        .on('click', function(event, d) {
          event.stopPropagation();
          // Only advance if this child is reachable from current position
          const currentId = iState.path.length > 0
            ? iState.path[iState.path.length - 1].id
            : TREE.id;
          if (d.source.data.id !== currentId) return;
          treeWalkAdvance(d.target.data, d.target);
          iRender(); // keep interactive panel in sync
        });
    }
  });

  const nodeG = g.append('g').attr('class','tg-nodes');
  nodes.forEach(d => {
    const data = d.data, typeCfg = nodeTypeCfg(data.type);
    const nw = d.nodeW, nh = d.nodeH, nx = d.px - nw/2, ny = d.py;

    const fo = nodeG.append('foreignObject')
      .datum(d)
      .attr('class', 'tg-tree-node')
      .attr('x',nx).attr('y',ny).attr('width',nw).attr('height',nh)
      .style('overflow', 'hidden')
      .style('border-radius', '10px');

    const card = fo.append('xhtml:div')
      .attr('xmlns','http://www.w3.org/1999/xhtml').attr('class','tg-node-card')
      .style('background', typeCfg.bg)
      .style('border',     typeCfg.border || 'none')
      .style('border-left',typeCfg.borderLeft || typeCfg.border || 'none');

    if (data.type === 'start') {
      card.append('xhtml:div').attr('class','tg-card-title')
        .style('color', typeCfg.titleColor).style('font-family', CONFIG.fonts.mono)
        .style('font-size','13px').style('font-weight','600')
        .style('letter-spacing','2px').style('text-transform','uppercase')
        .style('text-align','center').text(data.title);

      // Start node: click to reset walk
      fo.style('cursor', 'pointer')
        .on('mouseenter', function() {
          d3.select(this).select('div').style('box-shadow', `0 0 0 2px ${activePalette().accent}`);
        })
        .on('mouseleave', function() {
          d3.select(this).select('div').style('box-shadow', null);
        })
        .on('click', function(event) {
          event.stopPropagation();
          treeWalkReset();
        });
      return;
    }

    const eb = card.append('xhtml:div').attr('class','tg-card-eyebrow').style('color', typeCfg.eyebrowColor);
    eb.append('xhtml:span').text(data.eyebrow || typeCfg.label || data.type.toUpperCase());
    if (isNodeNew(data)) eb.append('xhtml:span').attr('class','tg-new-badge').text('NEW');
    card.append('xhtml:div').attr('class','tg-card-title').style('color', typeCfg.titleColor).text(data.title || '');
    if (data.hint) card.append('xhtml:div').attr('class','tg-card-hint').style('color', typeCfg.hintColor).text(data.hint);

    // Click any node to jump the walk directly to that node
    fo.style('cursor', 'pointer')
      .on('mouseenter', function() {
        if (!iState.choices.length || activePathIds().has(data.id)) return;
        d3.select(this).select('div').style('outline', `1.5px solid ${activePalette().accent}`).style('outline-offset', '-1.5px');
      })
      .on('mouseleave', function() {
        d3.select(this).select('div').style('outline', null).style('outline-offset', null);
      })
      .on('click', function(event) {
        event.stopPropagation();
        treeWalkJumpTo(data, d);
      });
  });
}

function rebuildTree() {
  if (!treeG) return;
  treeG.selectAll('*').remove();
  treeLayout = buildLayout(TREE);
  renderFullTree(treeG, treeLayout);
  highlightActivePath();
}

/* ── Tree walk: find path from root to a given node ID ── */
function findPathToNode(targetId, node, pathSoFar) {
  const current = pathSoFar.concat(node);
  if (node.id === targetId) return current;
  if (!node.children) return null;
  for (const child of node.children) {
    const result = findPathToNode(targetId, child, current);
    if (result) return result;
  }
  return null;
}

/* ── Tree walk: jump directly to any node by clicking it ── */
function treeWalkJumpTo(targetData, layoutNode) {
  const fullPath = findPathToNode(targetData.id, TREE, []);
  if (!fullPath || fullPath.length === 0) return;

  // fullPath[0] is TREE (start), fullPath[1] is first question, etc.
  // iState.path starts from the first question (not start node).
  // choices[i] is the decision taken FROM path[i].
  const newPath    = [];
  const newChoices = [];

  for (let i = 1; i < fullPath.length; i++) {
    newPath.push(fullPath[i]);
    if (i < fullPath.length - 1) {
      newChoices.push({
        label: fullPath[i + 1].edgeLabel || fullPath[i + 1].type,
        node:  fullPath[i + 1],
      });
    }
  }

  iState.path    = newPath;
  iState.choices = newChoices;
  highlightActivePath();
  panToNode(layoutNode);
  wRender();
  iRender();
}


function wCountDescendants(node) {
  if (!node.children || node.children.length === 0) return 0;
  return node.children.reduce((sum, c) => sum + 1 + wCountDescendants(c), 0);
}

function wEdgeClass(label) {
  if (label === 'YES') return 'tg-yes';
  if (label === 'NO')  return 'tg-no';
  return 'tg-def';
}

function wMakeEpill(label, ghost) {
  const pill = document.createElement('div');
  pill.className = 'tg-walk-epill ' + (ghost ? 'tg-ghost' : wEdgeClass(label));
  pill.textContent = label || '';
  return pill;
}

function wMakeConnector(label, ghost) {
  const row = document.createElement('div');
  row.className = 'tg-walk-connector';
  const line = document.createElement('div');
  line.className = 'tg-walk-vline';
  row.appendChild(line);
  if (label) row.appendChild(wMakeEpill(label, ghost));
  return row;
}

function wMakeHistoryNode(nodeData, stepIndex) {
  const el = document.createElement('div');
  el.className = 'tg-walk-node';
  const ey = document.createElement('div');
  ey.className = 'tg-walk-ey';
  ey.textContent = nodeData.eyebrow || '';
  if (isNodeNew(nodeData)) {
    const badge = document.createElement('span');
    badge.className = 'tg-new-badge'; badge.textContent = 'NEW';
    ey.appendChild(badge);
  }
  el.appendChild(ey);
  const title = document.createElement('div');
  title.className = 'tg-walk-title';
  title.textContent = nodeData.title || '';
  el.appendChild(title);
  el.onclick = () => {
    iState.path    = iState.path.slice(0, stepIndex + 1);
    iState.choices = iState.choices.slice(0, stepIndex);
    highlightActivePath();
    wRender();
    iRender();
  };
  return el;
}

function wMakeGhostStub(nodeData) {
  const el = document.createElement('div');
  el.className = 'tg-walk-ghost';
  const gt = document.createElement('div');
  gt.className = 'tg-walk-gt';
  gt.textContent = (nodeData.eyebrow ? nodeData.eyebrow + ' — ' : '') + (nodeData.title || '');
  el.appendChild(gt);
  const count = wCountDescendants(nodeData);
  const gc = document.createElement('div');
  gc.className = 'tg-walk-gc';
  gc.textContent = count === 0 ? '↓ outcome' : '↓ ' + (count + 1) + ' nodes';
  el.appendChild(gc);
  return el;
}

function wRender() {
  const root = document.getElementById('tg-walk-root');
  if (!root) return;
  root.innerHTML = '';

  const p = activePalette();

  // iState.path[0] is always the first question (seeded by iReset).
  // Walk history = all nodes in iState.path except the last (current).
  // iState.choices[i] is the choice taken from iState.path[i].

  const firstQ = firstQuestion(TREE);
  const currentNode = iState.path.length > 0
    ? iState.path[iState.path.length - 1]
    : firstQ;

  // Render history steps
  // path[0] is step 0, path[1] is step 1, etc.
  // For each history node (all except last), show the node,
  // then ghost stubs for unchosen siblings, then the chosen connector.
  for (let i = 0; i < iState.path.length - 1; i++) {
    const histNode = iState.path[i];
    const chosenChild = iState.choices[i] ? iState.choices[i].node : null;
    const chosenLabel = iState.choices[i] ? iState.choices[i].label : '';

    root.appendChild(wMakeHistoryNode(histNode, i));

    // Unchosen siblings — render ghost stubs with their edge label
    if (histNode.children && chosenChild) {
      histNode.children.forEach(sibling => {
        if (sibling.id === chosenChild.id) return;
        const sibLabel = sibling.edgeLabel || sibling.type;
        root.appendChild(wMakeConnector(sibLabel, true));
        root.appendChild(wMakeGhostStub(sibling));
      });
    }

    // Chosen connector
    root.appendChild(wMakeConnector(chosenLabel, false));
  }

  // Current node
  const isOutcome = currentNode.type !== 'question' && currentNode.type !== 'start'
                 && !(currentNode.children && currentNode.children.length > 0);
  const typeCfg   = nodeTypeCfg(currentNode.type);

  if (!isOutcome) {
    const activeEl = document.createElement('div');
    activeEl.className = 'tg-walk-node tg-walk-active';
    const ey = document.createElement('div');
    ey.className = 'tg-walk-ey';
    ey.textContent = currentNode.eyebrow || '';
    if (isNodeNew(currentNode)) {
      const badge = document.createElement('span');
      badge.className = 'tg-new-badge'; badge.textContent = 'NEW';
      ey.appendChild(badge);
    }
    activeEl.appendChild(ey);
    const title = document.createElement('div');
    title.className = 'tg-walk-title';
    title.textContent = currentNode.title || '';
    activeEl.appendChild(title);
    if (currentNode.hint) {
      const hint = document.createElement('div');
      hint.className = 'tg-walk-hint';
      hint.textContent = currentNode.hint;
      activeEl.appendChild(hint);
    }
    root.appendChild(activeEl);

    // Choice cards
    if (currentNode.children && currentNode.children.length > 0) {
      const label = document.createElement('div');
      label.className = 'tg-walk-choices-label';
      label.textContent = 'Choose a path';
      root.appendChild(label);

      const choices = document.createElement('div');
      choices.className = 'tg-walk-choices';
      currentNode.children.forEach(child => {
        const btn = document.createElement('div');
        btn.className = 'tg-walk-choice ' + wEdgeClass(child.edgeLabel || '');
        const cl = document.createElement('div');
        cl.className = 'tg-walk-cl';
        cl.textContent = child.edgeLabel || '→';
        btn.appendChild(cl);
        btn.onclick = () => {
          iState.choices.push({ label: child.edgeLabel || child.type, node: child });
          iState.path.push(child);
          highlightActivePath();
          if (treeLayout) {
            const ln = treeLayout.nodes.find(n => n.data.id === child.id);
            if (ln) panToNode(ln);
          }
          wRender();
          iRender();
          // Scroll walk panel to bottom so the active node and choices are visible
          const panel = document.getElementById('tg-panel-walk');
          if (panel) panel.scrollTop = panel.scrollHeight;
        };
        choices.appendChild(btn);
      });
      root.appendChild(choices);
    }

  } else {
    // Outcome card
    const card = document.createElement('div');
    card.className = 'tg-walk-outcome';
    card.style.background  = typeCfg.bg;
    card.style.border      = typeCfg.border || 'none';
    card.style.borderLeft  = typeCfg.borderLeft || typeCfg.border || 'none';

    const badge = document.createElement('div');
    badge.className = 'tg-outcome-badge';
    badge.textContent = typeCfg.label || currentNode.type.toUpperCase();
    const accent = typeCfg.accent || CONFIG.nodeTypes[currentNode.type]?.accent;
    badge.style.color = accent; badge.style.background = typeCfg.bg; badge.style.borderColor = accent;
    card.appendChild(badge);

    const ey = document.createElement('div');
    ey.className = 'tg-outcome-eyebrow'; ey.style.color = typeCfg.eyebrowColor;
    ey.textContent = currentNode.eyebrow || typeCfg.label || '';
    card.appendChild(ey);

    const t = document.createElement('div');
    t.className = 'tg-outcome-title'; t.style.color = typeCfg.titleColor;
    t.textContent = currentNode.title;
    card.appendChild(t);

    if (currentNode.hint) {
      const h = document.createElement('div');
      h.className = 'tg-outcome-hint'; h.style.color = typeCfg.hintColor;
      h.textContent = currentNode.hint;
      card.appendChild(h);
    }

    const resetBtn = document.createElement('button');
    resetBtn.className = 'tg-reset-btn'; resetBtn.innerHTML = '↺ Start over';
    resetBtn.onclick = () => { treeWalkReset(); };
    card.appendChild(resetBtn);
    root.appendChild(card);
  }

  // Back button
  if (iState.path.length > 1) {
    const back = document.createElement('button');
    back.className = 'tg-back-btn'; back.textContent = '← Back';
    back.onclick = () => {
      iState.path    = iState.path.slice(0, -1);
      iState.choices = iState.choices.slice(0, -1);
      highlightActivePath();
      wRender();
      iRender();
      const panel = document.getElementById('tg-panel-walk');
      if (panel) panel.scrollTop = panel.scrollHeight;
    };
    root.appendChild(back);
  }
}

/* ── Interactive engine ── */
function firstQuestion(node) {
  if (node.type !== 'start') return node;
  return (node.children && node.children[0]) ? node.children[0] : node;
}
function iReset() {
  iState.path    = [ firstQuestion(TREE) ];
  iState.choices = [];
  iRender();
  wRender();
}
function iChoose(child) {
  iState.choices.push({ label: child.edgeLabel || child.type, node: child });
  iState.path.push(child);
  highlightActivePath();
  if (treeLayout) {
    const layoutNode = treeLayout.nodes.find(n => n.data.id === child.id);
    if (layoutNode) panToNode(layoutNode);
  }
  iRender();
  wRender();
}
function iGoTo(index) {
  iState.path    = iState.path.slice(0, index + 1);
  iState.choices = iState.choices.slice(0, index);
  highlightActivePath();
  iRender();
  wRender();
}

function iRender() {
  const root = document.getElementById('tg-interactive-root');
  if (!root) return;
  root.innerHTML = '';

  const current   = iState.path[iState.path.length - 1];
  const depth     = iState.path.length;
  const isOutcome = current.type !== 'question' && current.type !== 'start'
                 && !(current.children && current.children.length > 0);
  const typeCfg   = nodeTypeCfg(current.type);
  const edges     = edgeColors();
  const p         = activePalette();

  // breadcrumb
  if (iState.choices.length > 0) {
    const bc = document.createElement('div');
    bc.className = 'tg-breadcrumb';
    const s0 = document.createElement('span');
    s0.className = 'tg-crumb-link'; s0.textContent = 'Start';
    s0.onclick = () => iGoTo(0);
    bc.appendChild(s0);
    iState.choices.forEach((c, i) => {
      const sep = document.createElement('span');
      sep.className = 'tg-crumb-sep'; sep.textContent = '›';
      bc.appendChild(sep);
      const lbl = document.createElement('span');
      const isLast = i === iState.choices.length - 1;
      lbl.className = isLast ? 'tg-crumb-current' : 'tg-crumb-link';
      lbl.style.color = edges[c.label] || edges.default;
      if (!isLast) lbl.onclick = () => iGoTo(i + 1);
      lbl.textContent = c.label;
      bc.appendChild(lbl);
    });
    root.appendChild(bc);
  }

  // progress dots
  const pr = document.createElement('div');
  pr.className = 'tg-progress-row';
  const totalDots = Math.max(depth, 4);
  for (let i = 0; i < totalDots; i++) {
    const dot = document.createElement('div');
    dot.className = 'tg-progress-dot';
    dot.style.background = i < depth - 1 ? p.border : i === depth - 1 ? p.accent : p.surface;
    dot.style.transform  = i === depth - 1 ? 'scale(1.5)' : 'scale(1)';
    if (i < depth - 1) dot.onclick = () => iGoTo(i + 1);
    pr.appendChild(dot);
  }
  root.appendChild(pr);

  // card
  const card = document.createElement('div');

  if (!isOutcome) {
    card.className = 'tg-i-card';
    const eyebrow = document.createElement('div');
    eyebrow.className = 'tg-i-step-label'; eyebrow.textContent = current.eyebrow || '';
    if (isNodeNew(current)) {
      const badge = document.createElement('span');
      badge.className = 'tg-new-badge'; badge.textContent = 'NEW';
      eyebrow.appendChild(badge);
    }
    card.appendChild(eyebrow);
    const q = document.createElement('div');
    q.className = 'tg-i-question'; q.textContent = current.title;
    card.appendChild(q);
    if (current.hint) {
      const h = document.createElement('div');
      h.className = 'tg-i-hint'; h.textContent = current.hint;
      card.appendChild(h);
    }
    const optRow = document.createElement('div');
    optRow.className = 'tg-options-row';
    (current.children || []).forEach(child => {
      const btn = document.createElement('button');
      const isYes = child.edgeLabel === 'YES', isNo = child.edgeLabel === 'NO';
      const ec = edgeColors();
      const customColor = child.edgeLabel && !isYes && !isNo ? (ec[child.edgeLabel] || null) : null;
      btn.className = 'tg-opt-btn ' + (isYes ? 'tg-yes' : isNo ? 'tg-no' : '');
      if (customColor) btn.style.borderColor = customColor;
      const icon = document.createElement('span');
      icon.className = 'tg-opt-icon';
      icon.textContent = isYes ? '✓' : isNo ? '✗' : '→';
      btn.appendChild(icon);
      btn.appendChild(document.createTextNode(child.edgeLabel || child.eyebrow || child.type));
      btn.onclick = () => iChoose(child);
      optRow.appendChild(btn);
    });
    card.appendChild(optRow);

  } else {
    card.className = 'tg-outcome-card';
    card.style.background = typeCfg.bg;
    card.style.border     = typeCfg.border || 'none';
    card.style.borderLeft = typeCfg.borderLeft || typeCfg.border || 'none';

    const badge = document.createElement('div');
    badge.className = 'tg-outcome-badge';
    badge.textContent = typeCfg.label || current.type.toUpperCase();
    const accent = typeCfg.accent || CONFIG.nodeTypes[current.type]?.accent;
    badge.style.color = accent; badge.style.background = typeCfg.bg; badge.style.borderColor = accent;
    card.appendChild(badge);

    const ey = document.createElement('div');
    ey.className = 'tg-outcome-eyebrow'; ey.style.color = typeCfg.eyebrowColor;
    ey.textContent = current.eyebrow || typeCfg.label || '';
    card.appendChild(ey);

    const t = document.createElement('div');
    t.className = 'tg-outcome-title'; t.style.color = typeCfg.titleColor;
    t.textContent = current.title;
    card.appendChild(t);

    if (current.hint) {
      const h = document.createElement('div');
      h.className = 'tg-outcome-hint'; h.style.color = typeCfg.hintColor;
      h.textContent = current.hint;
      card.appendChild(h);
    }

    const reset = document.createElement('button');
    reset.className = 'tg-reset-btn'; reset.innerHTML = '↺ Start over';
    reset.onclick = () => {
      treeWalkReset();
      iReset();
    };
    card.appendChild(reset);
  }

  root.appendChild(card);

  if (iState.path.length > 1) {
    const back = document.createElement('button');
    back.className = 'tg-back-btn'; back.textContent = '← Back';
    back.onclick = () => iGoTo(iState.path.length - 2);
    root.appendChild(back);
  }
}

/* ── Public API (called from inline onclick handlers) ── */
window.treage = {
  setMode(mode) {
    const isTree  = mode === 'tree';
    const isWalk  = mode === 'walk';
    const isInter = mode === 'interactive';
    document.getElementById('tg-panel-tree').classList.toggle('tg-visible', isTree);
    document.getElementById('tg-panel-walk').classList.toggle('tg-visible', isWalk);
    document.getElementById('tg-panel-interactive').classList.toggle('tg-visible', isInter);
    document.getElementById('tg-btn-tree').classList.toggle('active', isTree);
    document.getElementById('tg-btn-walk').classList.toggle('active', isWalk);
    document.getElementById('tg-btn-interactive').classList.toggle('active', isInter);
    const sub    = document.getElementById('tg-header-sub');
    const subMob = document.getElementById('tg-secondary-sub');
    const subText = isTree  ? CONFIG.subtitle + ' — Scroll to zoom · Drag to pan · Click edges to walk.'
                  : isWalk  ? CONFIG.subtitle + ' — Click a path to advance. Click any history node to go back.'
                  :           CONFIG.subtitle;
    sub.textContent = subText;
    if (subMob) subMob.textContent = subText;
    if (isTree && fitView) setTimeout(() => fitView(300), 50);
    if (isWalk)  wRender();
  },

  toggleTheme() {
    currentTheme = currentTheme === 'dark' ? 'light' : 'dark';
    document.body.classList.toggle('tg-light', currentTheme === 'light');
    applyPalette();
    rebuildTree();
    iRender();
    try { localStorage.setItem('treage-theme', currentTheme); } catch(e) {}
  },

  toggleLegend() {
    const btn       = document.getElementById('tg-legend-toggle');
    const secondary = document.getElementById('tg-header-secondary');
    const expanded  = secondary.classList.contains('tg-expanded');
    secondary.classList.toggle('tg-collapsed', expanded);
    secondary.classList.toggle('tg-expanded',  !expanded);
    btn.classList.toggle('tg-collapsed', expanded);
    btn.classList.toggle('tg-expanded',  !expanded);
  },
};

/* ── Init ── */
function init() {
  /* Inject styles and DOM shell — must be first */
  document.documentElement.lang = 'en';
  document.head.insertAdjacentHTML('beforeend', TREAGE_STYLES);
  document.body.innerHTML = TREAGE_BODY;

  // Restore saved preference
  try {
    if (localStorage.getItem('treage-theme') === 'light') {
      currentTheme = 'light';
      document.body.classList.add('tg-light');
    }
  } catch(e) {}

  applyPalette();

  document.getElementById('tg-header-title').textContent = CONFIG.title;
  document.getElementById('tg-header-sub').textContent   = CONFIG.subtitle + ' — Scroll to zoom · Drag to pan · Click edges to walk.';
  document.getElementById('tg-header-icon').innerHTML    = CONFIG.icon || '';
  document.title = CONFIG.title;

  // Legend (desktop) + mobile clone
  const legendEl       = document.getElementById('tg-legend');
  const legendMobileEl = document.getElementById('tg-legend-mobile');
  Object.values(CONFIG.nodeTypes).forEach(t => {
    if (!t.legendLabel) return;
    const mkItem = () => {
      const item = document.createElement('div');
      item.className = 'tg-legend-item';
      item.innerHTML = `<span class="tg-legend-dot" style="background:${t.accent}"></span>${t.legendLabel}`;
      return item;
    };
    legendEl.appendChild(mkItem());
    legendMobileEl.appendChild(mkItem());
  });

  // Mobile secondary row — subtitle
  const secondarySub = document.getElementById('tg-secondary-sub');
  if (secondarySub) secondarySub.textContent = CONFIG.subtitle + ' — Scroll to zoom · Drag to pan · Click edges to walk.';

  // Full tree
  container = document.getElementById('tg-canvas');
  treeSvg = d3.select(container).append('svg').attr('width','100%').attr('height','100%');
  treeSvg.append('defs');
  treeG = treeSvg.append('g').attr('class','tg-main-g');

  treeZoom = d3.zoom().scaleExtent([0.08, 2.5])
    .on('zoom', e => treeG.attr('transform', e.transform));
  treeSvg.call(treeZoom);

  fitView = function(duration = 600) {
    const bounds = treeG.node().getBBox();
    if (!bounds.width || !bounds.height) return;
    const cw = container.clientWidth, ch = container.clientHeight, pad = 48;
    const scale = Math.min((cw-pad*2)/bounds.width, (ch-pad*2)/bounds.height, 1.0);
    const tx = cw/2 - scale*(bounds.x + bounds.width/2);
    const ty = pad + (ch-pad*2 - scale*bounds.height)/2 - scale*bounds.y;
    treeSvg.transition().duration(duration)
      .call(treeZoom.transform, d3.zoomIdentity.translate(tx,ty).scale(scale));
  };

  document.getElementById('tg-zoom-in') .onclick = () => treeSvg.transition().duration(280).call(treeZoom.scaleBy, 1.3);
  document.getElementById('tg-zoom-out').onclick = () => treeSvg.transition().duration(280).call(treeZoom.scaleBy, 0.77);
  document.getElementById('tg-zoom-fit').onclick = () => fitView(400);
  document.getElementById('tg-export-png').onclick = () => exportSVG();

  treeLayout = buildLayout(TREE);
  renderFullTree(treeG, treeLayout);
  setTimeout(() => fitView(500), 100);
  window.addEventListener('resize', () => fitView(300));

  iReset();
}

/* ── SVG Export ── */
function exportSVG() {
  const svgEl = treeSvg.node();
  if (!svgEl) return;

  // Bounding box of drawn content
  const g    = svgEl.querySelector('.tg-main-g');
  const bbox = g ? g.getBBox() : { x: 0, y: 0, width: svgEl.clientWidth, height: svgEl.clientHeight };
  const pad  = 40;
  const W    = Math.ceil(bbox.width  + pad * 2);
  const H    = Math.ceil(bbox.height + pad * 2);

  // Clone, set explicit dimensions + viewBox cropped to content
  const clone = svgEl.cloneNode(true);
  clone.setAttribute('width',   W);
  clone.setAttribute('height',  H);
  clone.setAttribute('viewBox', `${bbox.x - pad} ${bbox.y - pad} ${W} ${H}`);
  clone.setAttribute('xmlns',   'http://www.w3.org/2000/svg');

  // Reset pan/zoom transform so export is at natural scale
  const cloneG = clone.querySelector('.tg-main-g');
  if (cloneG) cloneG.setAttribute('transform', '');

  // Resolve CSS variables and inline styles for self-contained rendering
  const cs = getComputedStyle(document.documentElement);
  const get = (v, fallback) => cs.getPropertyValue(v).trim() || fallback;
  const bgColor = get('--color-bg', '#0d0f14');

  // Background rect
  const bgRect = document.createElementNS('http://www.w3.org/2000/svg', 'rect');
  bgRect.setAttribute('x',      bbox.x - pad);
  bgRect.setAttribute('y',      bbox.y - pad);
  bgRect.setAttribute('width',  W);
  bgRect.setAttribute('height', H);
  bgRect.setAttribute('fill',   bgColor);
  clone.insertBefore(bgRect, clone.firstChild);

  // Inline card styles with resolved values (foreignObject needs self-contained CSS)
  const styleEl = document.createElementNS('http://www.w3.org/2000/svg', 'style');
  styleEl.textContent = [
    '* { box-sizing: border-box; margin: 0; padding: 0; }',
    '.tg-node-card { width:100%; height:100%; border-radius:10px; padding:11px 14px; display:flex; flex-direction:column; justify-content:center; overflow:hidden; box-sizing:border-box; font-family:sans-serif; }',
    '.tg-card-eyebrow { font-family:monospace; font-size:9.5px; font-weight:600; text-transform:uppercase; letter-spacing:1px; margin-bottom:5px; display:flex; align-items:center; gap:5px; }',
    '.tg-new-badge { background:rgba(254,197,20,0.15); color:#fec514; border:1px solid rgba(254,197,20,0.3); border-radius:4px; font-size:8px; padding:1px 4px; letter-spacing:0.5px; }',
    '.tg-card-title { font-size:12px; font-weight:500; line-height:1.45; font-family:sans-serif; }',
    '.tg-card-hint  { font-size:10.5px; font-weight:300; font-style:italic; margin-top:5px; line-height:1.4; font-family:sans-serif; }',
  ].join('\n');
  clone.insertBefore(styleEl, clone.firstChild);

  // Fix SVG text elements that use var(--font-mono) via CSS class — won't resolve after serialization
  clone.querySelectorAll('.tg-edge-label, text').forEach(el => {
    const ff = el.getAttribute('font-family') || '';
    if (!ff || ff.includes('var(')) el.setAttribute('font-family', 'monospace');
  });

  // Serialize and trigger download
  const svgStr  = new XMLSerializer().serializeToString(clone);
  const blob    = new Blob([svgStr], { type: 'image/svg+xml;charset=utf-8' });
  const url     = URL.createObjectURL(blob);
  const a       = document.createElement('a');
  a.href        = url;
  a.download    = (CONFIG.title || 'treage').replace(/[^a-z0-9]/gi, '-').toLowerCase() + '.svg';
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', init);
} else {
  init();
}

})();